### ISSUE TITLE
XMLName element has invalid  xml tag

### ISSUE THREAD

**Issue by mileusna** [GoComply/xsd2go#19]
After convert, I get this kind of struct type
```
type MyType struct {
	XMLName xml.Name `xml:myType`

        Name `xml:"name"`
        Address `xml:"address"`
        // etc.
}
```

It procudes lint warning `struct field tag 'xml:myType' not compatible with reflect.StructTag.Get: bad syntax for struct tag value` since it needs double quotes around `myType`.

So instead of `xml:myType` it should be `xml:"myType"`

Fields inside struct has correct xml tag, only the XMLName element has bad syntax tag.

**Comment by isimluk** [comment]
Do we want to introduce the lint you mention in the CI?

**Comment by isimluk** [comment]
Thank You!
