### ISSUE TITLE
Difference compared to `xgen`?

### ISSUE THREAD

**Issue by BatmanAoD** [GoComply/xsd2go#2]
Hi, I was wondering what the difference(s) are between this project and [`xgen`](https://github.com/xuri/xgen). This project is of course much younger, and it doesn't appear that you intend to generate code for languages other than Go, but I can't tell from looking at the READMEs and your blog post whether you have a specific goal that `xgen` doesn't meet.

**Comment by isimluk** [comment]
Hello! Thank You for bringing `xgen` to my attention. I haven't been able to find `xgen` when I was searching for this particular problem. It seems that `xgen` is only about 5 months older than xsd2go. I will have to play with `xgen` little bit to see if there are any kind of differences.

**Comment by isimluk** [comment]
From a quick try on [SCAP schemas](https://github.com/OpenSCAP/openscap/tree/maint-1.3/schemas) it seems that `xgen` is not handling well circular dependencies across various XSD files. That shouldn't be too hard to fix though.

**Comment by isimluk** [comment]
For the cross XSD dependencies (xsd:import) tag it seems that `xgen` is copying imported datatypes to the importing file, effectively creating duplicates within a project that needs to parse various XSD with some commonality in a dependency tree.

**Comment by isimluk** [comment]
Otherwise, I would say `xgen` is pretty cool.

**Comment by isimluk** [comment]
Feel free to re-open to restart discussion.
