### ISSUE TITLE
panic: Type xsd:unsignedInt not implemented

### ISSUE THREAD

**Issue by andig** [GoComply/xsd2go#20]
Happens on 

    <xs:element minOccurs="0" name="waiting" type="xs:unsignedInt"/>

Could you give a hint where I should start looking into the code?

**Comment by r-vasquez** [comment]
I've had the same issue with long, anyURI, date, dateTime. In case you find something let me know so we can add more types.

**Comment by isimluk** [comment]
All five types mentioned in this issue are now supported. Thank You for reporting those!
