### ISSUE TITLE
ISO-8859-1 encoded XSD failes.

### ISSUE THREAD

**Issue by kranzo** [GoComply/xsd2go#6]
While processing nested XSD (all ISO-8859-1) i get the following error.

Error decoding XSD: xml: encoding "ISO-8859-1" declared but Decoder.CharsetReader is nil

with some time or some hints where to search i'm happy to add a PR to fix this.

**Comment by isimluk** [comment]
Hello @kranzo, Thank You for the report. Are You willing to share a reproducer? Perhaps a small cut/subset of Your XSD is enough?

**Comment by redhatrises** [comment]
Looks like CharsetReader may need to be used. See https://github.com/golang/go/issues/8937
