### ISSUE TITLE
Cannot resolve type reference: integer

### ISSUE THREAD

**Issue by redhatrises** [GoComply/xsd2go#7]
./gocomply_xsd2go convert schema.xsd github.com/gocomply/goswid swid
Processing 'schema.xsd'
	Parsing: schema.xsd
	Parsing: xmldsig-core-schema.xsd
panic: Cannot resolve type reference: integer

goroutine 1 [running]:
github.com/gocomply/xsd2go/pkg/xsd.(*Element).compile(0xc0002e4538, 0xc0001f8300, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/element.go:136 +0x337
github.com/gocomply/xsd2go/pkg/xsd.(*Sequence).compile(0xc0001e5dc0, 0xc0001f8300, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/sequence.go:21 +0x76
github.com/gocomply/xsd2go/pkg/xsd.(*ComplexType).compile(0xc0001c39e8, 0xc0001f8300, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/types.go:73 +0x3fc
github.com/gocomply/xsd2go/pkg/xsd.(*Schema).compile(0xc0001f8300)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/schema.go:54 +0xc5
github.com/gocomply/xsd2go/pkg/xsd.(*Workspace).loadXsd(0xc0001275e0, 0xc00013f480, 0x17, 0x0, 0x0, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/workspace.go:51 +0x37d
github.com/gocomply/xsd2go/pkg/xsd.(*Import).load(0xc0001aa870, 0xc0001275e0, 0x89c035, 0x1, 0xc0002a22f8, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/schema.go:256 +0xbe
github.com/gocomply/xsd2go/pkg/xsd.(*Workspace).loadXsd(0xc0001275e0, 0x7fff0106e988, 0xa, 0x0, 0x0, 0x0)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/workspace.go:47 +0x31f
github.com/gocomply/xsd2go/pkg/xsd.NewWorkspace(0xc00013ee20, 0x1f, 0x7fff0106e988, 0xa, 0x2, 0xc00013ee20, 0x1f)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd/workspace.go:20 +0x84
github.com/gocomply/xsd2go/pkg/xsd2go.Convert(0x7fff0106e988, 0xa, 0x7fff0106e993, 0x1a, 0x7fff0106e9ae, 0x4, 0xc00019db58, 0x945860)
	/home/testing/go/src/github.com/gocomply/xsd2go/pkg/xsd2go/generate.go:12 +0x19a
github.com/gocomply/xsd2go/cli/cmd.glob..func2(0xc00015bb80, 0x0, 0xc000119d80)
	/home/testing/go/src/github.com/gocomply/xsd2go/cli/cmd/cmd.go:33 +0x82
github.com/urfave/cli.HandleAction(0x814c00, 0x8bf500, 0xc00015bb80, 0xc00015bb80, 0x0)
	/home/testing/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.Command.Run(0x89f033, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8b632f, 0x44, 0x0, ...)
	/home/testing/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
github.com/urfave/cli.(*App).Run(0xc0001e8540, 0xc000136000, 0x5, 0x5, 0x0, 0x0)
	/home/testing/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
github.com/gocomply/xsd2go/cli/cmd.Execute(0xffffffff, 0xc00010e058)
	/home/testing/go/src/github.com/gocomply/xsd2go/cli/cmd/cmd.go:18 +0x10a
main.main()
	/home/testing/go/src/github.com/gocomply/xsd2go/cli/gocomply_xsd2go/main.go:8 +0x22

**Comment by isimluk** [comment]
Can You provide the xsd file, please?

**Comment by isimluk** [comment]
> Can You provide the xsd file, please?

Nevermind, I think I have fixed it anyway.
